// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Tecnico", Schema = "dbo")]
	public class Tecnico
	{
		[Column("TecnicoId" , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     TecnicoId  { get; set; } // int
		[Column("Nombre"    , CanBeNull    = false                                                             )] public string  Nombre     { get; set; } = null!; // varchar(50)
		[Column("Codigo"    , CanBeNull    = false                                                             )] public string  Codigo     { get; set; } = null!; // varchar(50)
		[Column("SueldoBase"                                                                                   )] public decimal SueldoBase { get; set; } // decimal(10, 2)
		[Column("SucursalId"                                                                                   )] public int     SucursalId { get; set; } // int

		#region Associations
		/// <summary>
		/// FK_Tecnico_Sucursal
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(SucursalId), OtherKey = nameof(DataModel.Sucursal.SucursalId))]
		public Sucursal Sucursal { get; set; } = null!;

		/// <summary>
		/// FK_TecnicoElemento_Tecnico backreference
		/// </summary>
		[Association(ThisKey = nameof(TecnicoId), OtherKey = nameof(TecnicoElemento.TecnicoId))]
		public IEnumerable<TecnicoElemento> TecnicoElementos { get; set; } = null!;
		#endregion
	}
}
