// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("TecnicoElemento", Schema = "dbo")]
	public class TecnicoElemento
	{
		[Column("TecnicoElementoId", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int TecnicoElementoId { get; set; } // int
		[Column("TecnicoId"                                                                                          )] public int TecnicoId         { get; set; } // int
		[Column("ElementoId"                                                                                         )] public int ElementoId        { get; set; } // int
		[Column("Cantidad"                                                                                           )] public int Cantidad          { get; set; } // int

		#region Associations
		/// <summary>
		/// FK_TecnicoElemento_Elemento
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(ElementoId), OtherKey = nameof(DataModel.Elemento.ElementoId))]
		public Elemento Elemento { get; set; } = null!;

		/// <summary>
		/// FK_TecnicoElemento_Tecnico
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(TecnicoId), OtherKey = nameof(DataModel.Tecnico.TecnicoId))]
		public Tecnico Tecnico { get; set; } = null!;
		#endregion
	}
}
